---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-db-super-user
  namespace: external-secrets
spec:
  encryptedData:
    password: AgC6JWJPdx/wJRxju8Ev2goh0ge+1W1KvRTEBpvP0Etn9XLrqVRVe1JEKhzyKX4t0iuGjeRagBSdPjvBhVIoIlw+ufh3opc+QaSQz8hoqlHwlf8PrTP0ZPc++Am3bkOgZYnYydd7VGsuyF5H2HULfShSXP+SI4dre5oc+Rsql7c4oCYRzIHUYEU/aQzo8BxEhxnZgBu0Hs6mZf6w15gNBFp9PKeNTZ+i6r8foIgdZ0AIm5zL/fDOYkMQ+M5ds0bBqXwZnbKZsq8TdsX9iEEw8DaPQviZY8UxkVB6Ik1wYRwBQbF4BZ+zXvQxlfR0e/PlEii1FOs8cu42fX32dgEVRclkpgyJ3MvQCPBrfUAmVcDCWqnOEA8OhEzmPuDBwSbhaBEvSYmRsrlb3FRULuZlLy0byPrj1JgPLvOHdbUZm9XVyIKIok/eEGSOaZHs5/CuVinhxthOz9HsVpo8ebUCmeZAASUid6W2Y0R4NBKbwhfQg03S6vgSU5gmTHE3H/1NybHYMlrLYgHDLsmbSthN2IZlClhslzjlEmlqyKw8sSdLPEUPATm0bBPwZKlnEUlUeRiAsDz2CVvmDXp49x4GN92Dpk0y+k0i6K7PBGz0Zs7G2mjSc387lgvqEhL8X+3+8DMC36WbInUMmi0loB517+JMn8HfHH2WRfkfceBd/ocDiU7omioR+gvBzbTrPaBBTsaQYuDkJhAAS9ZJU36yG3LDOU8LFPWqbVYlNwlWJw01zxW8hQXEFxzmDGQ=
    user: AgAQfgqhpcg4yJdTyDTtIttJ7nKv4eax7uIpOfvBqVw6LIt3+IcrT9v3qAjy8u9MXVITgs4HVv6RGyWd7+t7YU0ggvrhRQiB0ULBcTYKIfH7rH126/2xNZI/hZ4UdCEWH5rH+AHkjCUoyXl+slCE9foeveXIO22elCWMhYlpIs7rp2sR6XXxnz4SYP8ilc3fAWQ/Ge9AD/NUoe6yPFzuKzi4KOfs9Yhzajh0jH0K9Hq+mX0UZzGU07aL1sJOTgIrLy2OWXO/fI2Zz7fKq0mOVhT0t+v4UTofFpM9jUV52/yA9ZbK2L+vsLM7A8ViIt4YaKhuPd8i7xjNbF+DtiJzV/WGdlfFgAfjxmsWlwa509hdne06nHdb157gJLy4UU8nerP+IBM7B1NyXKCAUJ1yVPIdwh5gw12k4nrbEe+Jp5lFFz0xa4Tv1RLdGWnZGCoP7vqC/nIpOhngQQwV+oIDjuOYvzbAjjzSvc64u30s0zLT81B2RDu9za61IXqzUOhX7Akb+o1KRA7yIuYnkp2YP5z4hkze+1FC0iIZcl9miTiJ+35hZOoUJ34qe456RI1Rhk8fDwqE5v3MKqSn/1EyHkfLQ3RFie6UBma4Hlv0QZucgKrK4QKlqVP80UUnVAPqVSFaSc1qWq1I5txC3u7O8ceCNAFzWWNc1gXDSbZqS9bWM43mTETKB75KP8YYMD+Ul6JWCTPVynJM1bog
  template:
    metadata:
      creationTimestamp: null
      name: vault-db-super-user
      namespace: external-secrets
