{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata":
    {
      "name": "vault-db-user",
      "namespace": "vaultwarden-app",
      "creationTimestamp": null,
    },
  "spec":
    {
      "template":
        {
          "metadata":
            {
              "name": "vault-db-user",
              "namespace": "vaultwarden-app",
              "creationTimestamp": null,
            },
        },
      "encryptedData":
        {
          "password": "AgA0GKbxOBTHLbRSVN9jqHuHMa52V6tBGQHoCBVSb/7IU6SpZPKwhf2pqLjdpia394Z6Oa9Fro7+AUbU5EZB1RCN5VO2Ey1NP6cvJgAsG44lT6MiS1ur+5saj+h0rre4K1BD3W+G/z2b5eRMt8YeWuwkrnbGrJqSp0h1saCLa0Pmp6vurHDmmfz+gA7YmjohiFNAy7OBfUlgcJJdpHebzeQQR6EqFjl5sGmkND/x6bQodJ33xQ1sYpLkqSq3JBSf7KAcWhR4b5vjimpsxT2b2XkS0xsKTBGL+7LeNQ7twtaZ1/jOVmoznMVnw+9VctgAjMP+V8x3+lqmPkhCwl5veIlynjCopC+vL5VLcPxORAXyLJvoMAOsb4czJnLraeLFNx5rDRKoFvkhxC2IHdYiA4BgGIHYua1J52orhqTQmrDvkOr1d/K8YA783fyDg9jX+V2tglkVM0zwWIpYlkVzHxrVRj60UIA0rqsAGTobU9zbpX4XHTq3bjoLyVpHfZYmf6Cngex2XSXNs5GNlA3zxRlMLnm4awZeQMIrgVYEL3V6jGEOdf/mqVaJEupn6b3bsCPfEIykbAE6mUJIpccfEqz468BvYglv82zEu4e12vkU6NdC9vQN1Ood3nSnD4+/2lgGmLo8M/PpZae7GNNqMQLhkePoPwims15FcWy4NZq9ygkgC/6ZVEZ6jN7LtgketVRMM0rg6F9W4VcUUIc71ZebLiYN7Glu",
          "username": "AgAhXQnH5s+2os3757avIRMeKL5JzxOJxK2bBi1Z2f/i5ANskEMnE+mEI/vtboYP2GaiA9v4TTKOyjb7suE+6FNhHnfxzzilazq8XV2in7LhqzfiiPCikAKOtm/Gjq50QwrZ84WGNNT+ivbZnqxeMPvSTPksgICfxSezDLorqxLMx57pGX9InxqFgVjadgOlnJSbBqK1v/FhGk9cMOhcegfz//+0HzbrR1hYS3Z+QU5x/QsUbcY+vidpMkCxUrW9+uWJghXapj08a1Irwytd6bc2tRdh7LiLvf3b0ZW+4rejLZ3gPv/U5kwVqgvqJKWRkxGnlL8MWOlMKQhQgRpKPfM+RnXZbaNa9t1Vf0icdnNmHHZr2Va3fFwKcXVoHS1OTHUUZpompHhkThjrMgwOVtFRr2Q7VwbIBHxLhDX934qcojpOw2sbQOSBDIECiwOorNS1cq5SuMRqnwOCejMpdlD5N8XW//zAIeDxkbvIrwP2Dd683UuQZ9BuQhWQ7vKye+S2EB2n/bqGy1G8HS4NtvXUKbRHr1r9liLiGG5nxgTJrZNZw5K9FfkfOLTRJai26UU51IV7+1OEjNoOXlP7B2ySEEt6AzlbZPrRp3X3BZTR9cKEInGFa9ulYZfkW/bQUi3gznahv+1q4qltHJK8VOuoLp6hkv3qpSp9uoo9V2ijKBV4k5oy1HcNxQeuve9UiECbcyn0bzP1I7FJREAP",
        },
    },
}
