{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata":
    {
      "name": "vault-db-super-user",
      "namespace": "vaultwarden-app",
      "creationTimestamp": null,
    },
  "spec":
    {
      "template":
        {
          "metadata":
            {
              "name": "vault-db-super-user",
              "namespace": "vaultwarden-app",
              "creationTimestamp": null,
            },
        },
      "encryptedData":
        {
          "password": "AgAw87a71zNznqj6ixCCZoRPkPfpis1Wnm1Mq8+CF5oHJIlqAkCf9E2WjZHIj4HMudOI2TWPrVm4cH8LZp59VUEk7RsWaLDUCNkjfvnI4pixv7jhf50PiC+FOyOCne64Y1ejKGy2UyiMUf3/7b8GAg3bZ0IkYiWMG9am0Nu6yn6QoQPi66RQMqZLxVGTpxk1X4tFyrqO3/ldxus905pKsIBf1Uq3cGRRGui1xTr32d4EW0OeNGABt1j4I0SOOrmZeBZRMDu8r3q5KXLpPmwIDQCmsgrDC4ldYQPNvxYWtQl+zO6V2DhGzNYFvYHrRhgqoVDn5f59NlpGdhPA7ISPaV/OuqUOxS36XSOw59lRGZJ9oZYV7NEU4UjGvIE+usBHqnSHVwyk9oJj4wILIeYaQODSMulBSYok/zraS0dfXtelNw8zik8jcIxtlJ+RyyUKiPnk8DWAOjTvtRuoRVKGVYSZzSQEeRls2gsenjRiSOJMYBU5qNDpcMpZNhvBMejX4f2DXvxIgmDJNfVCyyPJzS2NuduVqesQnSf84LleDQVkON4FGpQ3L2EnVu1Dww2tDgYdSaZpisf1Y421sNzeCIvFMpPwbPk0VPVpN6oyWpJOlF99jxLsSuj54eWc7kXHUlwK3agQDRd3tPYN6wQkwZ5MgSvSd1rPlMqaj5yS6OX0XSKRRP+aTLiAuz0KOSh/VG3kE8bL4uXVgannyD5RNY5+TRRJ1yT/uFnv/w==",
          "username": "AgAC96aPRhTngOpY8YYX1H8g214ZkpiXQvuiK+cz7ppVtgRc8J0pfWa0pdaTe7qUn9Z9pKZ4U/QliB9zh7SPM8wHvXR7So0Bdn9eHDaan7bS/uSx8xSQjIIdRWbiN1A3pO21V5QMKMcnPtwRWlRRMjzfYFLzbzMBIiyxlhL5QBi+8PNHB+gAtsxF//7KH3sma4EA28oiqlgA3uGch3rADGUKg18VzeMzTYx40OVGqGB0Mp5eXueEps9jA2o4QBBsPh89isjuqmDB2Qd7Z9fVW6YTs5lr2NRyme1M5Gf5AjapGou6DmcC3/GnKTkEAYtzm6sEQ/xKfagQ5T3EXTD6Bx/HZhu2yu5kIIS6S7BFKyAJ6FyoVRGy0xDwxW57cEPyOjNdc8PX0Vs6CV3C3CybMbM4Jth9yvxf3Fn8NeahAgWyYRzARhVYVMZinuOfLhzHieMjONKdxdnEmPLaDQARYytedqQZta0ruBT2DkACPBKjlqc/y7XGzfc2z0es5HCnnOj8DEufGUbgj2ramb/fOoF78RJj/LyRvzvltZXX68znPV+gszp/R26omAKaWc8I4hVLiipoNedljVm8N3K6l0b4usjx7GB+Zp6XxG5y64Pf7W20wDPafJZwhwbuypA1Pg+eg86hR+hM3vD1EFvmxOHsmDvgxXfMfnxpypclKVy8B6S6/CfYKAqSUvwIg8lF/savWZPDmVSQuhJgHe3zwBP/BexE",
        },
    },
}
