apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
spec:
  description: "Keycloak DB Storage"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  instances: 1
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak-db-user

  postgresql:
    parameters:
      log_statement: "ddl" # Only log Create, Alter and Drop statements

  enableSuperuserAccess: false
  superuserSecret:
    name: keycloak-db

  storage:
    storageClass: longhorn
    size: 10Gi
