apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-db
spec:
  description: "Vaultwarden DB Storage"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  instances: 3
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: vaultwarden-app
      owner: vault-db-user

  postgresql:
    parameters:
      log_statement: "ddl" # Only log Create, Alter and Drop statements

  enableSuperuserAccess: false
  superuserSecret:
    name: vault-db-super-user

  storage:
    storageClass: longhorn
    size:
      15Gi

      #resources:
      #  requests:
      #  memory: ""
      #  cpu: ""

      #limits:
      #  memory: ""
      #  cpu: ""
