apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-db
  version: "16.4"
  component: database
  part-of: vaultwarden
  managed-by: cnpg
spec:
  description: "Vaultwarden DB Storage"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  instances: 3
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: vaultwarden-app
      owner: vault-db-user
      #secret:
      #  name: vault-db-user

  enableSUperuserAccesss: false
  superuserSecret:
    name: vault-db-super-user

  storage:
    storageClass: longhorn
    size:
      15Gi

      #resources:
      #  requests:
      #  memory: ""
      #  cpu: ""

      #limits:
      #  memory: ""
      #  cpu: ""
