global:
  enabled: true
  tlsDisable: false
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

affinity: ""

server:
  # Set the image for the vault server
  image:
    repository: "hashicorp/vault"
    tag: "1.17.3"
  
  # Set the resources for the vault server
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1
  
  # Set the readiness probe for the vault server
  readinessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
    scheme: HTTPS
  livenessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true"
    scheme: HTTPS
    initialDelaySeconds: 60

  # Set the extra volumes for the vault server these will be exposed in the path /vault/userconfig/<name>
  extraVolumes:
    - type: secret
      name: vault-internal-tls

  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-internal-tls/tls.crt

  dataStorage:
    enabled: true
    size: 5Gi
  auditStorage:
    enabled: false

  standalone:
    enabled: false

  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
    
    config: |
      ui = true
      cluster_name = prd-dct-vault

      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/vault-internal-tls/tls.crt"
        tls_key_file = "/vault/userconfig/vault-internal-tls/tls.key"
      }

      storage "raft" {
        path = "/vault/data"
        retry_join {
          leader_api_addr = "https://vault-0.vault-internal:8200"
          leader_ca_cert_file = "/vault/userconfig/vault-internal-tls/tls.crt"
          leader_client_cert_file = "/vault/userconfig/vault-internal-tls/tls.crt"
          leader_client_key_file = "/vault/userconfig/vault-internal-tls/tls.key"
        }
        retry_join {
          leader_api_addr = "https://vault-1.vault-internal:8200"
          leader_ca_cert_file = "/vault/userconfig/vault-internal-tls/tls.crt"
          leader_client_cert_file = "/vault/userconfig/vault-internal-tls/tls.crt"
          leader_client_key_file = "/vault/userconfig/vault-internal-tls/tls.key"
        }
        retry_join {
          leader_api_addr = "https://vault-2.vault-internal:8200"
          leader_ca_cert_file = "/vault/userconfig/vault-internal-tls/tls.crt"
          leader_client_cert_file = "/vault/userconfig/vault-internal-tls/tls.crt"
          leader_client_key_file = "/vault/userconfig/vault-internal-tls/tls.key"
        }
      }

  service_registration: "kubernetes"

ui:
  enabled: false
