global:
  enabled: true
  tlsDisable: false
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

affinity: ""

injector:
  enabled: true

server:
  # Set the image for the vault server
  image:
    repository: "hashicorp/vault"
    tag: "1.17.3"
  
  # Set the resources for the vault server
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1
  
  # Set the readiness probe for the vault server
  readinessProbe:
    enabled: false
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
    scheme: HTTPS
  livenessProbe:
    enabled: false
    path: "/v1/sys/health?sealedcode=204&standbycode=204&uninitcode=204"
    scheme: HTTPS
    initialDelaySeconds: 60

  # Set the extra volumes for the vault server these will be exposed in the path /vault/userconfig/<name>
  extraVolumes:
    - type: secret
      name: vault-internal-tls
    - type: secret
      name: vault-ca-tls

  extraEnvironmentVars:
    #VAULT_CACERT: /vault/userconfig/vault-ca-tls/ca.crt
    VAULT_TLS_CERT: /vault/userconfig/vault-internal-tls/tls.crt
    VAULT_TLS_KEY: /vault/userconfig/vault-internal-tls/tls.key

  dataStorage:
    enabled: true
    size: 5Gi

  auditStorage:
    enabled: false

  standalone:
    enabled: false

  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
    
      config: |
        ui = true
        cluster_name = "prd-dct-vault"
      
        listener "tcp" {
          tls_disable = 0
          address = "[::]:8200"
          cluster_address = "[::]:8201"

          tls_cert_file = "/vault/userconfig/vault-tls/tls.crt"
          tls_key_file = "/vault/userconfig/vault-tls/tls.key"

          # X-Forwarded-For configuration
          x_forwarded_for_authorized_addrs = "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
          x_forwarded_for_reject_not_authorized = "false"
          x_forwarded_for_reject_not_present = "false"

          tls_require_and_verify_client_cert = "false"
          tls_disable_client_certs = "true"
        }

        storage "raft" {
          path = "/vault/data"
        
          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
            # No CA needed as Let's Encrypt is trusted
            leader_client_cert_file = "/vault/userconfig/vault-tls/tls.crt"
            leader_client_key_file = "/vault/userconfig/vault-tls/tls.key"
          }
    
          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
            leader_client_cert_file = "/vault/userconfig/vault-tls/tls.crt"
            leader_client_key_file = "/vault/userconfig/vault-tls/tls.key"
          }
    
          retry_join {
            leader_api_addr = "https://vault-2.vault-internal:8200"
            leader_client_cert_file = "/vault/userconfig/vault-tls/tls.crt"
            leader_client_key_file = "/vault/userconfig/vault-tls/tls.key"
          }
        }

ui:
  enabled: true