keys:
  - &dc-tec age1k2kr92m8nad59shnvv07t4v54zpu9lrxmnj8a4vm36vgvhn36c6sqp50kc

creation_rules:
  - path_regex: infra/bootstrap/sealed-secrets/key/sealed-secrets-key.yaml$
    key_groups:
      - age:
          - *dc-tec
