apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  labels:
    name: cloudnative-pg
spec:
  project: applications
  source:
    repoURL: git@github.com/dc-tec/k8s-gitops.git
    targetRevision: feature/deploy-postgress
    path: infrastructure/cert-manager
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
