apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: vault-gateway
  namespace: vault-infra
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      hostname: vault.decort.tech
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      hostname: vault.decort.tech
      port: 443
      protocol: TLS    # Changed from HTTPS to TLS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Passthrough  # Changed from Terminate to Passthrough
---
apiVersion: gateway.networking.k8s.io/v1alpha2  # Note: TLSRoute is still alpha
kind: TLSRoute
metadata:
  name: vault-route
  namespace: vault-infra
spec:
  parentRefs:
    - name: vault-gateway
      sectionName: https
  hostnames:
    - "vault.decort.tech"
  rules:
    - backendRefs:
        - name: vault-active
          port: 8200
---
# Keep the HTTP to HTTPS redirect
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vault-route-redirect
  namespace: vault-infra
spec:
  parentRefs:
    - name: vault-gateway
      sectionName: http
  hostnames:
    - "vault.decort.tech"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301