apiVersion: cert-manager.io/v1alpha1
kind: ClusterIssuerPolicy
metadata:
  name: auto-approve-vault-certs
spec:
  targets:
    - issuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: cert-manager-self  # Your self-signed cluster issuer
  conditions:
    - commonName: "Vault Root CA"
      namespace: "vault-infra"
---
# Add RBAC for auto-approval
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-vault-approver
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests"]
  verbs: ["approve"]
  resourceNames: ["vault-ca", "vault-internal-tls"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-vault-approver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-vault-approver
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager