apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  labels:
    name: longhorn
spec:
  project: infrastructure
  source:
    repoURL: git@github.com/dc-tec/k8s-gitops.git
    targetRevision: feature/configure-longhorn
    path: main
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
