---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-prd
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/managed-by: manual
    app.kubernetes.io/component: cluster-infrastructure
spec:
  acme:
    email: roel@decort.tech
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-prd-key
    solvers:
      - selector:
          dnsZones:
            - "decort.tech"
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-dns-api
              key: token
