apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    name: argocd
spec:
  project: core
  sources:
    - repoURL: git@github.com/dc-tec/k8s-gitops.git
      targetRevision: main
      path: kubernetes/apps/core/argocd
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
