apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    name: external-secrets
spec:
  project: infrastructure
  source:
    repoURL: git@github.com/dc-tec/k8s-gitops.git
    targetRevision: main
    path: kubernetes/apps/infrastructure/external-secrets
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
