apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argocd
  labels:
    name: openbao
spec:
  project: workload
  source:
    repoURL: git@github.com/dc-tec/k8s-gitops.git
    targetRevision: main
    path: kubernetes/apps/workload/openbao
  destination:
    namespace: openbao-infra
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: openbao-agent-injector-cfg
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
