---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-db
  namespace: keycloak
spec:
  encryptedData:
    password: AgBYko/rdBzWTOmzByivBVKjhY82f6aDqB361PSb/t+QkBPGG2gtEswZxlZW2i7HXWNqr46i4yKOURsFlrEkQHjRsexhoc7jGoNEwn9kHHmZoau/uATJ3oo3zQMkYvgoXusoogO8rRIH4h6rZrVnLcdgYkgshkMtgIcxnwJmbtfkEvQdWbSBUt5pEidE9ur8uC7/zfgBQKsu+O2+1n7PNZmFCXN0Srv7IW4bwhL+Z6BWlyJhMT1VeOAqHTWlCVrJxAyCqBn1f/tIzW2BKjlRW8l/68Bu2GQqbhqDehULycV2Dy02QVQfwXzk5A+9X9s/w2bJehrkNHUR/xvJlUTR1POmcE0T8Ep5QWYzuV44UsrTJyPMQLwh2Eebbpv55+StwHjxsgUQoRvSrooy5G82zOOXdIWiASCxOfEhXLvf5/rfPYwpPbIL6st9PoS+6c0l1wp/C2gCavKZQumhonh/1g0XdfPPAcXAGbRrxSuluSmAcaWSnCeOoQqneD0dXTGAN76q3+93DL421iAjEizaSOMAl+zt+xqPDvV29XiYPernx2jhNU9Zb1Hy6zDQcomKoEodY3GPhQrJQMNIqwDMhSsC6egPjLWrNv83XkqhfWxw71VyogU8ALPIqmIwFUEM0xtHcZtLPA5kPwJLo/adiBmLvP/mH9EfZkgjbkErXNYu89mXxq2gSsCjuA7NzywMA32E7P96PMKC2CRecxkDPLWFsKiq7Vsqv4kgLMMA7Fld
    username: AgCEyIBrxpvODtkZ0oYp8HbACSO5DiytY5k3UF1M8hgBkEkx9lmm/uRcabfUB5Lj9yKDE3svbLNIvGCi4UNZLcMLCvlonVyCH56YJfaLsBWzxm8NHXUBRYofgFcglUyAd8kTnZeE2KDlIkr1kSMClpEQmegkx0TJr+k6yYv8ZBVGZyQXPg0hklNupTQgl+viuLNIi8D4td8lAjr1IsWcvpAjP+QrzCFCvFdmqdX0dR3DW8Rw7EU1cofLxw9odD6k6BgbioiITLsrUqaxzhtLDEj3sIR86gZyNDGutAK8o/QPNujklnIece8H8KBqlubIJuLYQSMjBg3QfDkFrS4Ot6OWxLzelKIx6SmobtjWY0nRO8od0q6As9wjPt/NTxTpahUGhrd5yRf7CqTejruB/g3OseOXecmFq/jrAupPQxXeRmEJPqikBd9Yy2qSEGvef8ZKXKCbtAGv5rHBvjqA++pI/2siyhXr8aBp3Ocdo73NOu4WED9CCYSqKPq9n1KOW300op5AW46xRFB1tqADQ9GJSqwOMJL3PwoMfyfAW7SMid18IW62KKQv+fLJHqCursdHs5wsKdyIRw2GYIf/KFuFYbF03OiktV60r9h5g3T7PmNrz02mlq1tP2J+FpAMJrXrA5wqWYjlz9jtGIjfBMPuZtt5GKtanywQ6ZYYTd9zn/VROP4dcuAOQpLVjbJhRWkfHsu9vGU2NDPX84ehZSJq
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-db
      namespace: keycloak
