apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/namespace.yaml
  - base/gateway.yaml

helmCharts:
  - name: rancher
    includeCRDs: true
    releaseName: rancher-stable
    namespace: cattle-system
    version: 0.29.1
    repo: https://releases.rancher.com/server-charts/stable
    valuesFile: config/values.yaml
