# External TLS termination configuration
tls: "external"

# Rancher Server hostname
hostname: "rancher.decort.tech"

# Replica count for high availability
replicas: 1

# Anti-affinity for HA deployment
antiAffinity: "preferred"

# Resources configuration
resources:
  limits:
    cpu: "1000m"
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "512Mi"

ingress:
  enabled: false