apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-infrastructure
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com/dc-tec/k8s-gitops.git
        revision: main
        directories:
          - path: apps/core/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: '{{path.basename}}'
