apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-backend
spec:
  provider:
    azurekv:
      environmentType: PublicCloud
      vaultUrl: https://kv-lab-infra-prd-westeu.vault.azure.net/
      tenantId: 9efbb2a3-8e4f-4a4b-ae0b-e53fe5049a2a
      authSecretRef:
        clientId:
          name: az-kv-secrets
          key: client-id
          namespace: external-secrets
        clientSecret:
          name: az-kv-secrets
          key: client-secret
          namespace: external-secrets
