apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-backend
spec:
  provider:
    azurekv:
      environmentType: PublicCloud
      authType: ServicePrincipal
      vaultUrl: https://kv-lab-infra-prd-westeu.vault.azure.net/
      authSecretRef: az-kv-secret
      auth:
        clientId: client-id
        clientSecret: client-secret
