---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: talos-bucket-secrets
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBtSJDCqwEFzRzub+coftf8flM8yN/36KLmMsUw0f0tJ0vjL1ZJGYX27fdCZOuyO9sPhD1dyz9P8EfxTRZbRY8fjMy1FT+fT/Qm1pyoTmn6+X74oXySzvuaKi7TLHTv1VXoE8qGSAaXEcZ2mrPbKjQOaHwxepqa5r+2Io6eh5eZC48y1UWrgJEXFieUEDwDYlYzZHT1CEvA0REs3QrTcS0ZyodDSlM7DHzUsOb6LhkE57gORB125NGzNA9yaX99MTsWrGLa4BU057Cu1wEaMC3J27kfgk7+H3duWvAuD4KKFXZWSMOKXQKTqNV9DhHgQ7jdO20RfQEg/wQK58+hi6L2ila3gT3LuZSooPDPSr5oEpABSn2UbGelf9CKh3IuOi44oCJS8HCzbOmoSeN/qTTMcLMIhJ0s5ULDlDWsmfTszTyCIligo9FDEzIiVGd62RvsMyC9GLh0HOrR3LN9YHrsnP5ZcHzwjJ4ccTFq7ozr67fpig/EZCVx+1AgxjE371MqpHPkwCcUD/BQUF65R6q3G0Q0DnRHCSMY5tJQXTnDY4z37caapNYGJ5lYkTGw0WH5jzrtCuFkvMe4AR2yLz+GGhBUuhMs/wPscxRpb0P54TAw9oufOEnrfsk1z3+avj8zAPqQ7vh3jNdLTi0sEwADLiYtSo/protvbWykl+U+K5JrGKzXJFws21LsjlHXvGlEyLKt8giLVxio0+jzFVZw4/dSoNI0x3B+
    AWS_SECRET_ACCESS_KEY: AgAfV9wlFzfeMYyGKjG/MC7+83g+mY39955e2VQI9Ah3amTomnFjTQ/9bVhLf65cuQpQNmb9kac3ME8ZoQTr3Pxu9C2IsGxKbXJhpzKloHnn5qGTvaDYPVT35w7ucsZ1kJWAtZGE9+GggW4ZmyL5FhU4FFNHteNhuegzpZQ+gc0XiO3SNae+7QuPr8BKdcPlUIQBVjTc6BIcJ4gfGyvDbDW1gvlZMS09NCaubfynTLHVYWfBPMzUfPC/e44Mti4hHYYhg9+MjRkZtcCDdCzZWgxxIBEN56M4nUp6KmLRzowsJ/f3pidmDAdBfKqo0o6ruQsUtamsu1ijSdabmKfMK189cRyHhgQYBpPaFr0sTJmebxFRAV5gTllv4HASTmEr/Zol9MFE8p17yrKZeU0fHGSjhDvY9TyifrNu9DB2xqNyEBYYzp7jGlIX2g0X96jvYwTPSib+zWauDroMuOV+q+mwVvlQmzfkaTX4tIrLVXc71UbEyTSkCl/c5hyvoJOaxLlucG+j/EB5YX3TZT7sBSQYe67MliRIcSmNJbFbhJ9wsU45IAL1BDezoAC4F3PLFAZuxxtv0JnW951kYJSwH2m+9ihA2TUQXHsBQHIrtNKND4NXiVlCUNznp2dXYiSI20f4JrGAWCGXhiSomKJciShAAsxV2fGo/fxE9BW+al+qmW5kMFrkHmOfS4BmicnLqNK12JYy+Wax0MPafSvJDAGrBx+PhBCVRya8P8AUvtdZ
  template:
    metadata:
      creationTimestamp: null
      name: talos-bucket-secrets
      namespace: default
