apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/cluster-issuer-prd.yaml
  - base/cluster-issuer-staging.yaml
  - base/cluster-issuer-self.yaml
  - config/secrets/cloudflare-api.yaml

helmCharts:
  - name: cert-manager
    includeCRDs: true
    releaseName: cert-manager
    namespace: cert-manager
    version: v1.16.3
    repo: https://charts.jetstack.io
    valuesInline:
      installCRDs: true
      extraArgs:
        - "--enable-gateway-api"
