apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  app.kubernetes.io/name: cert-manager
  app.kubernetes.io/managed-by: manual
  app.kubernetes.io/component: cluster-infrastructure
spec:
  acme:
    solvers:
      - selector:
          dnsZones:
            - "decort.tech"
        dns01:
          route53:
            region: eu-central-1
            accessKeyIDSecretRef:
              name: prd-aws-route53-credentials
              value: access-key-id
            secretAccessKeySecretRef:
              name: prd-aws-route53-credentials
              value: secret-access-key
            role: arn:aws:iam::649665367473:role/cert-manager
