apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dct-dev-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: dct-dev-ca
  subject:
    organizations:
      - "deCort.tech"
    organizationalUnits:
      - "Platform Services"
  secretName: dct-dev-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
