apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.yaml
  - base/cluster-issuer-staging.yaml
  - base/cluster-issuer-prd.yaml
  - config/controller-config.yaml
