apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - base/cluster-issuer-prd.yaml
  - base/cluster-issuer-staging.yaml

helmCharts:
  - name: cert-manager
    includeCRDs: true
    releaseName: cert-manager
    namespace: cert-manager
    version: 1.14.2
    repo: https://charts.jetstack.io
    valuesInline:
      configs:
        cm:
          kustomize.buildOptions: --enable-helm
      installCRDs: true
      globals:
        leaderEelection:
          namespace: cert-manager
      extraArgs:
        - "--feature-gates=ExperimentalGatewayAPISupport=true"
