apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/namespace.yaml
  - base/gateway.yaml
  - base/certificate.yaml
  - base/serviceaccount.yaml
  - base/snapshot.yaml
  - config/secrets/pkcs12-secret.yaml
  - config/secrets/openbao-backup-secrets.yaml

helmCharts:
  - name: openbao
    includeCRDs: true
    releaseName: openbao
    namespace: openbao-infra
    version: 0.12.0
    repo: https://openbao.github.io/openbao-helm
    valuesFile: config/values.yaml
