apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: prometheus
            path: kubernetes/apps/infrastructure/prometheus
            namespace: monitoring
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
      labels:
        app.kubernetes.io/name: '{{name}}'
        app.kubernetes.io/part-of: monitoring
    spec:
      project: infrastructure
      source:
        repoURL: git@github.com:dc-tec/k8s-gitops.git
        targetRevision: feat/monitoring-stack
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true