apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.2/manifests/install.yaml
  - base/gateway.yaml
  - base/namespace.yaml
  - ../../argocd/projects/core.yaml
  - ../../argocd/projects/infrastructure.yaml
  - ../../argocd/projects/workloads.yaml
  - ../../argocd/repositories/k8s-gitops.yaml

patches:
  - path: overlays/argocd-cm.yaml
  - path: overlays/argocd-cmd-params-cm.yaml
  - path: overlays/argocd-rbac-cm.yaml
