---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api
  namespace: cert-manager
spec:
  encryptedData:
    token: AgCefkxiq9twp7J+MxkbZjNe2zQ1oLak9NYno/b8oBbnODv4mQOFTzcCa5CT/q6mJRdotW2BHHjoCF2c9SgYQEotw01oLSzKQ7O9qpJp9SBxjDmu7KzDUgJLTavK+fNHR/07VjUb4tEHU5TnH2ZiGe8hTdq77eeBFycN75e3+dhTE/ywFR9TIFH1khncCgF86szgemRUsA+tQ7GVzERrYB5PdBgJbFnESXrm4LRqXwaqj5LbMjrzTrcLN8EFRHk4TLAqxOlt2ki3EHi9PtaSsezuqLGFMq1h7iLk9PdlocclLsbtUxGD0f1zB2/5VKa0RKfGRT4XrmIWIzweTb8/No+SJiiUukXeYM/P3F5/ndcwCYCTTcS9ZkVE1Dhce8DctP9gRx/qVEYlV5oBCS0Feb/P95sXQncq2RFNJWJJVENzsXcALMy/tn1SuvRXvcyRZuban+SAyU7uA5wXPUms2A9Uwvkw8iqJRfvNMHN2KP2hcFiqYCjdtiuKyi4BX1wTKE2XBdXQzAhuwHvPfyrNTT07kuzg8RmHTZVVwYLMmT+NtogrrbKG5hldlJUuPPLvzbv/2iuBREUAj9dLDt/DFMA/V+uEKIH/MyUykIpW6WeUnf9CNMcwDivgGs6vrX2Vj15EBUYvdF0IMxEnSG8r7sOZ7Nv2u/EXBf1QY6nYqyW8DpINmeH1znHQhM24g8+Kt2NrBYXZvI7noUfnNYYc52jZ2rTwka3cK0BejCJdaxsqYYBN/KXPbm4Z
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api
      namespace: cert-manager
