---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openbao-backup-secrets
  namespace: openbao-infra
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgDLRlEEKMr5dbZspY3yIgddrjBGcDWx+/Z0mDtac1GZ8TGRAeBmDLpo8/f/s3I2dZHnCth8TRi2SqYyvkiYOxK2PzMXCibCfhvPAE0ts4aOBpdUYDZLPf6lpM/QdOGxGATm8Me9T20jstEf3df+r8UIDD72x7DeuM7UV49atsV/N0SkOnOwNEYhW7r+IFiaPv7VHGLXbtSpPZhDdHdwxRiuSqjyCnHwUHmUtsCYVBL8NG6B70YBPihB2ljZwfmXLZjgAhnUBF1IoWT56O0MPeeecJPCdyMhP03eiOJmqMtQqDEyhh4s6egQ7HY/vGbbrykANhOsnrJM23t1A9wx8wzZxs70TgFMAG8p6fy5o9YQnqKr5jyLCRxMewbaS9v6Yu3mRr4mWD7eeMng0btIV28R0VkkALwTuHqJogYfouBa0C6fJj1Zwh6aWkO5Cwa70wungAtNQbaFy0waJR6TlmFfej+xQxmQjGyARHAgn/JTFwzF74NHARh/vwoFiByvAkl1Ej01f5aONH9z9LMzkRKMI3WZ3j7M2aXIMor2WHavptqSuMUykAv+NB4boUYwiIOvx5kzuclJErK3gyElsDlolEXWPsQoRXfnuyoMGMma2XbOs8KobdbGaz39IguJSnhKbY7daWBd/PxsW0uMppvhG9hh2v8uzKhDpXwNrp78yiguMmgCXtVRDzUCc6TpekaWBYXNf5RqyDlfY2XJRmhdFdfvQ8XqdXkJ
    AWS_SECRET_ACCESS_KEY: AgBnl2UZE/lJrVtf2KtYwdmc1LHg+yEQleQKxoolMaeIHsrXcmpFPV3PJiSuzgAZSJVOovqoaLnR3t73HSTHFHvruqV7dLpO0yDQYerniRsW3ASaZGXAB8D2InCY7sivGLnNhmE8YKpNx+TLRH1tXXVyQddqjzyumWgT9UkWlzzSlmiJHXiFnRwzLD9V1lsax5cDc9+/xfBi8wQIsLzKmB2nMvGpWLnOkJ5B0yMoxGlSgqZoy2tLWu4uqBYlOrzfLWaQwIogRm7E3BaWOZWcyZsJLqdg9kUtqp065KIQnS9Prm++AvGkSKj+0zbLYya5N3nEfSHw/0LNlSBdq7x+ULu4BwWqok9fNwkWkqrl1mAOqZNXDbYswtMn4rOD92N3NCW5lG6wvb3jDojcVylfE9DbAHr30O053VOFQYW+DjGUbvxgfESGOfsxW1O86pyIaNir7/EiIMjRPufa8yJdxpFMqvOnge1nHWDZAhd+2SStauWnfGS8Sh+O5ZbMm5Gy/nRTQUlRczofVhu3wm1lbtzMQO9pwxIOFHrkSdKhg5v85UXJzMtMb13202HTrqiHUnEkoyDzAShYpfoBGNCR8c4QcC6WJ1o5XqiBrFwH0g0AKIsHVgxM99BKg8Nlyc148cWC1d0AhXhZkYs0NBHnkEu5VO4dftr3IC01goNfm39mpS2badwULISgePHpKbUKJRcx+ihlzZ4dV/vjDqd6rMNdSyBW7MDSUcvjvSuUJK/s
  template:
    metadata:
      creationTimestamp: null
      name: openbao-backup-secrets
      namespace: openbao-infra
