apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  labels:
    name: sealed-secrets
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/dc-tec/k8s-gitops.git
    targetRevision: main
    path: infrastructure/secret-management/sealed-secrets
