---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-unseal
  namespace: vault-infra
spec:
  encryptedData:
    client_secret: AgA5ON5tGZnWywQmoF83w+URe/YpCZAvc3/jX/LeEFrxNZimGv7FcYIX74rS0/x7hOAA0oqeFRKA6KsXksHZQMdtW9tCaYcpeD8+PAh/6V/PIQG5TjshrIP6oDwIIKqq5vlIi3Fyp/fE2DbzGIZCc4n694F703a6mTbLssGrLUgUwOMkvBVinbjX08nzWqogXGgL5wmw+Oc3yAGyfo2tWsp3n3ZTtmDIPoyWuJsH44EsyVF35Svl/aoGhw+dI311O3nK+7P3jP0P+cSFJZF0X/OK9EAZX/n5ek/BYlcQmoioVmE2PgByh7eJmRCOohEjA2mVMJbAura2PgJekQYIUUAKqrL1WDvUSAgVwCqUHhXjiiIMN7aOmgJArw/k0uEe1ZOdakC3w2Qlhb7V/vAMKQU8Tj469qoCoT0u4PST8O+y+hnun5ytoOG80LCfC73PIf+Gt+/4igHXGqyPj/vbUkgSE39YQgfdkFEdpKvCVH7O7dY2i9LqOCAPKpu9mhuOvetUYV1JKWL1Q7wmYJpnYrw4mvKDOZRG7VeftDnW7yKC+hGkXLQ6zpZSsJuOodOYMR71VN4a5CxWMCaRTG2mbI6GtPHFdh96mCPNSwy/EHEQ7SKRlzGEykw0ffSLIqDc53R6M4GjMs3gIAmcyWOO8tGql5WLneYhcUXYmw4/ilqdrukVn18NsUptZVsx0sHZzJtN9Aq3wgWA6gL+AYKItl5gFUwasM0IWcXtHzeGmNdnn9dIjPdglc1Zqg==
  template:
    metadata:
      creationTimestamp: null
      name: vault-unseal
      namespace: vault-infra
