on:
  workflow_dispatch
  #schedule:
  #  - cron: "30 23 * * 6,3"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Renovate
        uses: renovatebot/github-action@v40.1.12
        with:
          configurationFile: renovate.json5
          renovate-version: full
          token: ${{ secrets.RENOVATE_TOKEN }}
