on:
  schedule:
    - cron: "0 5 * * 7"

jobs:
  renovate:
    runs-on: ubuntu:latest
    steps:
      - name: checkout
        uses: actions/checkout@4.1.6
      - name: Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          renovate-version: full
          token: ${{ secrets.RENOVATE_TOKEN }}
