on:
  schedule:
    - cron: "30 23 * * 6,3"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          renovate-version: full
          token: ${{ secrets.RENOVATE_TOKEN }}
