apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/namespace.yaml
  - base/gateway.yaml
  - base/certificate.yaml
  - base/vault-approver-rbac.yaml
  - config/secrets/pkcs12-secret.yaml
  - config/secrets/vault-unseal.yaml

helmCharts:
  - name: vault
    includeCRDs: true
    releaseName: vault
    namespace: vault-infra
    version: 0.29.1
    repo: https://helm.releases.hashicorp.com
    valuesFile: config/values.yaml
