# Create Root CA Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-ca
  namespace: vault-infra
  annotations:
    cert-manager.io/approve: "true"
    cert-manager.io/auto-approve: "true"
    cert-manager.io/cluster-issuer: cert-manager-self
    cert-manager.io/issuer-group: cert-manager.io
spec:
  isCA: true
  commonName: OpenBao Root CA
  secretName: vault-ca-tls
  privateKey:
    algorithm: ECDSA
    size: 384
    encoding: PKCS8
    rotationPolicy: Always
  duration: 87600h # 10 years
  renewBefore: 8760h # 1 year
  subject:
    organizations:
      - deCort.tech
    countries:
      - NL
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: pkcs12-password
        key: password
  issuerRef:
    name: cert-manager-self
    kind: ClusterIssuer
    #group: cert-manager.io
---
# Create CA Issuer using the Root CA
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: openbao-issuer
  namespace: vault-infra
spec:
  ca:
    secretName: openbao-ca-tls
---
# Create Vault Server Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-internal-tls
  namespace: openbao-infra
  annotations:
    cert-manager.io/approve: "true"
    cert-manager.io/auto-approve: "true"
spec:
  secretName: openbao-internal-tls
  duration: 720h # 30 days
  renewBefore: 360h # 15 days
  privateKey:
    algorithm: ECDSA
    size: 384
    encoding: PKCS8
    rotationPolicy: Always
  subject:
    organizations:
      - deCort.tech
    countries:
      - NL
  commonName: system:node:*.openbao-infra.svc.cluster.local
  dnsNames:
    - bao.openbao-infra.svc.cluster.local
    - bao.decort.tech
    - bao.openbao-infra.svc
    - openbao-infra
    - openbao
    - "*.openbao-internal"
    - "*.openbao-internal.openbao-infra.svc.cluster.local"
    - "*.openbao-internal.openbao-infra.svc"
  ipAddresses:
    - "127.0.0.1"
  usages:
    - server auth
    - client auth
    - digital signature
    - key encipherment
  issuerRef:
    name: openbao-issuer
    kind: Issuer
    group: cert-manager.io
